config/routes.rb
Tmr::Application.routes.draw do

  resources :parts
  resources :details

  root :to => 'details#index'

end

app/models/detail.rb
class Detail < ActiveRecord::Base
  attr_accessible :name, :parts_attributes, :transactions_attributes
  has_many :transactions
  has_many :parts, through: :transactions
  accepts_nested_attributes_for :parts, allow_destroy: true
  accepts_nested_attributes_for :transactions, allow_destroy: true
end

app/models/fastener_profile.rb
class FastenerProfile < ActiveRecord::Base
  include Fraction

  attr_accessible :diameter, :length, :material
  has_one :part, as: :profile, dependent: :destroy

  def name
    # "#{diameter.to_r}\" #{length.to_r}\"
    "#{fractionalize(diameter)}\" #{material} Screw X #{fractionalize(length)}\" LG."
  end

end

app/models/part.rb
class Part < ActiveRecord::Base
  attr_accessible :name
  has_many :transactions
  has_many :details, through: :transactions
  belongs_to :profile, polymorphic: true

  delegate :name, to: :profile, allow_nil: :true
  # delegate :quantity, to: :profile
  # delegate :ship_loose, to: :profile

end

app/models/rivet_profile.rb
class RivetProfile < ActiveRecord::Base
  include Fraction

  attr_accessible :diameter

  def name
    "#{fractionalize(diameter)}\" Blind Button Head Pop Rivet"
  end
  
end

app/models/stock_profile.rb
class StockProfile < ActiveRecord::Base
  include Fraction

  attr_accessible :dimensions, :length, :material
  has_one :part, as: :profile, dependent: :destroy

  def name
    "#{dimensions} #{material} Screw X #{fractionalize(length)}\" LG."
  end

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :detail
  belongs_to :part
  attr_accessible :quantity, :ship_loose, :part
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  def index
    @details = Detail.all
  end

  def new
    @detail = Detail.new
    @detail.parts.build
    @detail.transactions.build
  end

  def show
    @detail = Detail.find(params[:id])
  end

  def create
    @detail = Detail.new(params[:detail])
    @detail.save
    # @detail.transactions = params[:transactions_attributes]
    redirect_to :root
  end

  def destroy
    Detail.find(params[:id]).destroy
    redirect_to :root
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @part = Part.new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/details/index.html.erb
<div class="row">
  <div class="small-6 large-4 columns">
    <h1>Details</h1>

    <% @details.each do |detail| %>
      <p>
        <span><%= link_to detail.name, detail_path(detail) %></span>
        <span><%= link_to "Delete", detail_path(detail), method: :delete %></span>
      </p>
    <% end %>
    <%= link_to "Add Detail", new_detail_path %>
  </div>
</div>

app/views/details/new.html.erb
<%= form_for @detail do |f| %>
    <div class="row">
      <div class="large-2"><%= f.label :name, "Detail Name" %></div>
      <div class="large-8"><%= f.text_field :name %></div>

      <%= f.fields_for :parts do |builder| %>
        <fieldset>
          <div class="large-2"><%= builder.label :part, "Part Name" %></div>
          <div class="large-8"><%= builder.text_field :name %></div>
      <% end %>

      <%= f.fields_for :transactions do |builder| %>
          <div class="large-2"><%# builder.label :part, "Part Name" %></div>
          <div class="large-8"><%# builder.text_field :part %></div>

          <div class="large-2"><%= builder.label :quantity, "Quantity" %></div>
          <div class="large-8"><%= builder.text_field :quantity %></div>

          <div class="large-2"><%= builder.label :ship_loose, "Ship Loose" %></div>
          <div class="large-8"><%= builder.text_field :ship_loose %></div>
        </fieldset>
      <% end %>

      <%= f.submit "Create" %>
    </div>
<% end %>

app/views/details/show.html.erb
<div class="row">
  <div class="large-6 columns">
    <span class="label"><%= @detail.name %></span> <span class="detail-word">Detail</span>
  </div>
</div>
<div class="row">
  <table class="large-6 columns">
    <tr>
      <th>Part Name</th>
      <th>Quantity</th> 
      <th>Ship Loose</th>
    </tr>  
    <% @detail.transactions.each do |trans| %>
    <tr>
      <td><%= trans.part.name %></td>
      <td><%= trans.quantity %></td> 
      <td><%= trans.ship_loose %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title>TMR</title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar">
      <ul class="title-area">
        <li class="left"><h3><%= link_to "Details", :root %></h3></li>
      </ul>
    </nav>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/parts/edit.html.erb
<h1>Parts#eidt</h1>
<p>Find me in app/views/parts/eidt.html.erb</p>

app/views/parts/index.html.erb
<h1>Parts#index</h1>
<p>Find me in app/views/parts/index.html.erb</p>

<%= link_to "Add Part", new_part_path %>

app/views/parts/new.html.erb
<h1>Parts</h1>
<%= form_for @part do |f| %>
    <div class="row">
      <div class="large-2"><%= f.select "Type" %></div>
      <%= f.submit "Create" %>
    </div>
<% end %>

app/views/parts/show.html.erb
<h1>Parts#show</h1>
<p>Find me in app/views/parts/show.html.erb</p>